### ISSUE TITLE
create tour

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#298]
detecting if this is the first time user is logged in: https://community.auth0.com/t/redirect-to-onboarding-flow-after-sign-up-or-first-log-in/36689

**Comment by nicoalee** [comment]
in order to check that the user is logged in for the first time, need to add a rule in the auth0 dashboard:
https://community.auth0.com/t/how-to-check-whether-a-passwordless-sign-in-is-a-first-time-sign-in-or-not/56327/5
https://community.auth0.com/t/how-to-tell-if-a-user-is-logged-in-for-the-first-time/28813
https://auth0.com/docs/get-started/apis/scopes/sample-use-cases-scopes-and-claims#add-custom-claims-to-a-token
