### ISSUE TITLE
Relationship between Dataset and MetaAnalysis?

### ISSUE THREAD

**Issue by jdkent** [neurostuff/neurostore#31]
The `MetaAnalysis` database currently does not appear to reference the `Dataset` database, but in my mind I think `MetaAnalysis` should have an explicit relationship with the `Dataset` database, since the meta-analysis will perform operations on a dataset object. I'm probably missing something in my thought process.

https://github.com/neurostuff/neurostore/blob/3684138fcb985c393317bc42afb4a5cb8a95d7ac/neurostore/models/analysis.py#L8-L24

Should `data` in `MetaAnalysis`  have the same content as  `nimads_data` in `Dataset`?

https://github.com/neurostuff/neurostore/blob/3684138fcb985c393317bc42afb4a5cb8a95d7ac/neurostore/models/data.py#L24-L35

If `nimads_data` already contains the studies/analyses/points/images necessary for the meta-analysis, does this section contain redundant information?

```python
images = association_proxy("metanalysis_images", "image") 
points = association_proxy("metanalysis_points", "point") 
image_weights = association_proxy("metanalysis_images", "weight") 
point_weights = association_proxy("metanalysis_points", "weight") 
```

**Comment by tyarkoni** [comment]
> The MetaAnalysis database currently does not appear to reference the Dataset database, but in my mind I think MetaAnalysis should have an explicit relationship with the Dataset database, since the meta-analysis will perform operations on a dataset object.

Yes I think that's right. I don't think the current setup is by design; I just don't think I'd thought far enough ahead.

> Should data in MetaAnalysis have the same content as nimads_data in Dataset?

Probably this should just be a foreign key to the dataset table (a Dataset can be used by many analyses, but an analysis can only have one input dataset).

We also need a JSON field to store the analysis specification (e.g., parameters that get passed to NiMARE). Maybe that can be called `config` or `spec` or something.

> If nimads_data already contains the studies/analyses/points/images necessary for the meta-analysis, does this section contain redundant information?

Unclear... definitely we need to store weights somewhere, and those wouldn't go in the `Dataset`. But arguably they should go in the JSON analysis specification rather than having a relational representation in the DB. We've already broken the link between the `Dataset` and the other objects, so it would be weird to reintroduce it here. One static JSON file containing everything needed to configure the analysis to work with the `Dataset` is probably the way to go.

**Comment by jdkent** [comment]
closing for cleanup
