### ISSUE TITLE
auto-resolve duplicates from neurostore search

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#508]
I know we haven't worked much on the Neurostore search function, but even though the search is somewhat rudimentary, it can already be useful for doing a quick and dirty meta-analysis

One thing that would be useful to make this easier would be to auto-resolve duplicates from different sources.

i.e. if a study is found in both neurosynth and neuroquery, currently you have to resolve these duplicates one-by-one

Suggested changes:
- Show the `source` field in the duplicate resolution view
- If more than 1 duplicates are found, let the user select their source preferences in advances, and resolve using those prefs automatically. 
 
For example "10 duplicates were found from the following sources: `neurosynth`, `neuroquery`. Would you like to select a prefered source and select that as the chosen study?"

**Comment by nicoalee** [comment]
In our current implementation, we have implemented a `base-studies` endpoint which acts as a single parent to all versions of that study. This is implemented in the neurostore search so that we won't get duplicates appearing during the search.

However, this raises another question: When selecting studies from the neurostore search input, how does the user know which version they want to use for their meta-analysis? Do we choose the version for them automatically? @adelavega @jdkent

**Comment by adelavega** [comment]
Didn't we say that in a way this won't matter becauase they will be able to swtich which study they view at any time?

I think we can default to the study most likely to be correct: the last updated study

**Comment by jdkent** [comment]
This issue is resolved, but we do want to have a dropdown/comparison to switch between versions of studies, will open a new issue for a mechanism to do that.
