### ISSUE TITLE
Misc Feedback on Search & Curate

### ISSUE THREAD

**Issue by adelavega** [neurostuff/neurostore#621]
![Screenshot from 2023-11-15 14-54-34](https://github.com/neurostuff/neurostore/assets/2774448/c9e56b20-14d6-4fa8-b87b-2846152ccad9)

I have to scroll down to see Next button which was slightly confusing

**Comment by adelavega** [comment]
Also, I wonder if its best to collapse this list down by default, since the only action here is to click next? It made me think maybe I should review the papers one by one here

**Comment by adelavega** [comment]
I also wonder if we can give searches default names-- esp for NeuroStore searches

**Comment by adelavega** [comment]
![Screenshot from 2023-11-15 14-54-34](https://github.com/neurostuff/neurostore/assets/2774448/a04fa17e-57f2-4638-a94c-927ac0febecd)
This should say Journal not publication, correct?

**Comment by adelavega** [comment]
Minor feedback, maybe the full text link should be on the right, and if none is found, simply don't say anything. As is, it makse me think that something went wrong 
![Screenshot from 2023-11-15 14-57-31](https://github.com/neurostuff/neurostore/assets/2774448/109cfc57-8578-4e2b-a388-afec37594186)

**Comment by adelavega** [comment]
Does it make sense to let people edit stubs in Curation? Won't those changes me ignore if a matching BaseStudy is found?

**Comment by nicoalee** [comment]
after discussion:
 - remove review page and add summary info to the tag step. XX studies imported. 
 - prepopulate search name
 - choose method in search - a little confusing, should use a selection (like estimator gallery) so that everything appears on the page instead of a dropdown
 - Change resolve duplicates to REVIEW. No warnings
 - if no full text, just hide
 - remove edit buttons - just edit title, pmid and doi
